#!/usr/bin/env bash
set -eu

# URL:s taken from https://notofonts.github.io/

# Associative array (key-value pair)
# Sorted alphabetically as per keys

# Those fonts NOT directly under notofonts.github.io/fonts/
# are not yet migrated fully (apparently) and hence development build URLs are used below

# Problematic/unavailable URLs are marked TODO
declare -A font_urls=(
    ["NotoMusic-Regular.ttf"]=https://notofonts.github.io/music/fonts/NotoMusic/hinted/ttf/NotoMusic-Regular.ttf
    ["NotoNaskhArabic-Regular.ttf"]=https://notofonts.github.io/fonts/NotoNaskhArabic/hinted/ttf/NotoNaskhArabic-Regular.ttf
    ["NotoNastaliqUrdu-Regular.ttf"]=https://notofonts.github.io/fonts/NotoNastaliqUrdu/hinted/ttf/NotoNastaliqUrdu-Regular.ttf
    ["NotoSansAdlam-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansAdlam/hinted/ttf/NotoSansAdlam-Regular.ttf
    ["NotoSansAnatolianHieroglyphs-Regular.ttf"]=https://notofonts.github.io/anatolian-hieroglyphs/fonts/NotoSansAnatolianHieroglyphs/hinted/ttf/NotoSansAnatolianHieroglyphs-Regular.ttf
    ["NotoSansArabic-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansArabic/hinted/ttf/NotoSansArabic-Regular.ttf
    ["NotoSansArmenian-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansArmenian/hinted/ttf/NotoSansArmenian-Regular.ttf
    ["NotoSansAvestan-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansAvestan/hinted/ttf/NotoSansAvestan-Regular.ttf
    ["NotoSansBalinese-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansBalinese/hinted/ttf/NotoSansBalinese-Regular.ttf
    ["NotoSansBamum-Regular.ttf"]=https://notofonts.github.io/bamum/fonts/NotoSansBamum/hinted/ttf/NotoSansBamum-Regular.ttf
    ["NotoSansBassaVah-Regular.ttf"]=https://notofonts.github.io/bassa-vah/fonts/NotoSansBassaVah/hinted/ttf/NotoSansBassaVah-Regular.ttf
    ["NotoSansBatak-Regular.ttf"]=https://notofonts.github.io/batak/fonts/NotoSansBatak/hinted/ttf/NotoSansBatak-Regular.ttf
    ["NotoSansBengali-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansBengali/hinted/ttf/NotoSansBengali-Regular.ttf
    ["NotoSansBhaiksuki-Regular.ttf"]=https://notofonts.github.io/bhaiksuki/fonts/NotoSansBhaiksuki-Regular/hinted/ttf/NotoSansBhaiksuki-Regular.ttf
    ["NotoSansBrahmi-Regular.ttf"]=https://notofonts.github.io/brahmi/fonts/NotoSansBrahmi/hinted/ttf/NotoSansBrahmi-Regular.ttf
    ["NotoSansBuginese-Regular.ttf"]=https://notofonts.github.io/buginese/fonts/NotoSansBuginese/hinted/ttf/NotoSansBuginese-Regular.ttf
    ["NotoSansBuhid-Regular.ttf"]=https://notofonts.github.io/buhid/fonts/NotoSansBuhid/hinted/ttf/NotoSansBuhid-Regular.ttf
    ["NotoSansCanadianAboriginal-Regular.ttf"]=https://notofonts.github.io/canadian-aboriginal/fonts/NotoSansCanadianAboriginal/hinted/ttf/NotoSansCanadianAboriginal-Regular.ttf
    ["NotoSansCarian-Regular.ttf"]=https://notofonts.github.io/carian/fonts/NotoSansCarian/hinted/ttf/NotoSansCarian-Regular.ttf
    ["NotoSansCaucasianAlbanian-Regular.ttf"]=https://notofonts.github.io/caucasian-albanian/fonts/NotoSansCaucasianAlbanian/hinted/ttf/NotoSansCaucasianAlbanian-Regular.ttf
    ["NotoSansChakma-Regular.ttf"]=https://notofonts.github.io/chakma/fonts/NotoSansChakma/hinted/ttf/NotoSansChakma-Regular.ttf
    ["NotoSansCham-Regular.ttf"]=https://notofonts.github.io/cham/fonts/NotoSansCham/hinted/ttf/NotoSansCham-Regular.ttf
    ["NotoSansCherokee-Regular.ttf"]=https://notofonts.github.io/cherokee/fonts/NotoSansCherokee/hinted/ttf/NotoSansCherokee-Regular.ttf
    ["NotoSansChorasmian-Regular.ttf"]=https://notofonts.github.io/chorasmian/fonts/NotoSansChorasmian/hinted/ttf/NotoSansChorasmian-Regular.ttf
    ["NotoSansCoptic-Regular.ttf"]=https://notofonts.github.io/coptic/fonts/NotoSansCoptic/hinted/ttf/NotoSansCoptic-Regular.ttf
    ["NotoSansCuneiform-Regular.ttf"]=https://notofonts.github.io/cuneiform/fonts/NotoSansCuneiform/hinted/ttf/NotoSansCuneiform-Regular.ttf
    ["NotoSansCypriot-Regular.ttf"]=https://notofonts.github.io/cypriot/fonts/NotoSansCypriot/hinted/ttf/NotoSansCypriot-Regular.ttf
    ["NotoSansCyproMinoan-Regular.ttf"]=https://notofonts.github.io/cypro-minoan/fonts/NotoSansCyproMinoan/hinted/ttf/NotoSansCyproMinoan-Regular.ttf
    ["NotoSansDeseret-Regular.ttf"]=https://notofonts.github.io/deseret/fonts/NotoSansDeseret/hinted/ttf/NotoSansDeseret-Regular.ttf
    ["NotoSansDevanagari-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansDevanagari/hinted/ttf/NotoSansDevanagari-Regular.ttf
    ["NotoSansDuployan-Regular.ttf"]=https://notofonts.github.io/duployan/fonts/NotoSansDuployan/hinted/ttf/NotoSansDuployan-Regular.ttf
    ["NotoSansEgyptianHieroglyphs-Regular.ttf"]=https://notofonts.github.io/egyptian-hieroglyphs/fonts/NotoSansEgyptianHieroglyphs/hinted/ttf/NotoSansEgyptianHieroglyphs-Regular.ttf
    ["NotoSansElbasan-Regular.ttf"]=https://notofonts.github.io/elbasan/fonts/NotoSansElbasan/hinted/ttf/NotoSansElbasan-Regular.ttf
    ["NotoSansElymaic-Regular.ttf"]=https://notofonts.github.io/elymaic/fonts/NotoSansElymaic/hinted/ttf/NotoSansElymaic-Regular.ttf
    ["NotoSansEthiopic-Regular.ttf"]=https://notofonts.github.io/ethiopic/fonts/NotoSansEthiopic/hinted/ttf/NotoSansEthiopic-Regular.ttf
    ["NotoSansGeorgian-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansGeorgian/hinted/ttf/NotoSansGeorgian-Regular.ttf
    ["NotoSansGlagolitic-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansGlagolitic/hinted/ttf/NotoSansGlagolitic-Regular.ttf
    ["NotoSansGothic-Regular.ttf"]=https://notofonts.github.io/gothic/fonts/NotoSansGothic/hinted/ttf/NotoSansGothic-Regular.ttf
    ["NotoSansGrantha-Regular.ttf"]=https://notofonts.github.io/grantha/fonts/NotoSansGrantha/hinted/ttf/NotoSansGrantha-Regular.ttf
    ["NotoSansGujarati-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansGujarati/hinted/ttf/NotoSansGujarati-Regular.ttf
    ["NotoSansGunjalaGondi-Regular.ttf"]=https://notofonts.github.io/gunjala-gondi/fonts/NotoSansGunjalaGondi/hinted/ttf/NotoSansGunjalaGondi-Regular.ttf
    ["NotoSansGurmukhi-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansGurmukhi/hinted/ttf/NotoSansGurmukhi-Regular.ttf
    ["NotoSansHanifiRohingya-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansHanifiRohingya/NotoSansHanifiRohingya-Regular.ttf # TODO
    ["NotoSansHanunoo-Regular.ttf"]=https://notofonts.github.io/hanunoo/fonts/NotoSansHanunoo/hinted/ttf/NotoSansHanunoo-Regular.ttf
    ["NotoSansHatran-Regular.ttf"]=https://notofonts.github.io/hatran/fonts/NotoSansHatran/hinted/ttf/NotoSansHatran-Regular.ttf
    ["NotoSansHebrew-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansHebrew/hinted/ttf/NotoSansHebrew-Regular.ttf
    ["NotoSansImperialAramaic-Regular.ttf"]=https://notofonts.github.io/imperial-aramaic/fonts/NotoSansImperialAramaic/hinted/ttf/NotoSansImperialAramaic-Regular.ttf
    ["NotoSansIndicSiyaqNumbers-Regular.ttf"]=https://notofonts.github.io/indic-siyaq-numbers/fonts/NotoSansIndicSiyaqNumbers/hinted/ttf/NotoSansIndicSiyaqNumbers-Regular.ttf
    ["NotoSansInscriptionalPahlavi-Regular.ttf"]=https://notofonts.github.io/inscriptional-pahlavi/fonts/NotoSansInscriptionalPahlavi/hinted/ttf/NotoSansInscriptionalPahlavi-Regular.ttf
    ["NotoSansInscriptionalParthian-Regular.ttf"]=https://notofonts.github.io/inscriptional-parthian/fonts/NotoSansInscriptionalParthian/hinted/ttf/NotoSansInscriptionalParthian-Regular.ttf
    ["NotoSansJavanese-Regular.ttf"]=https://notofonts.github.io/javanese/fonts/NotoSansJavanese/hinted/ttf/NotoSansJavanese-Regular.ttf
    ["NotoSansKaithi-Regular.ttf"]=https://notofonts.github.io/kaithi/fonts/NotoSansKaithi/hinted/ttf/NotoSansKaithi-Regular.ttf
    ["NotoSansKannada-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansKannada/hinted/ttf/NotoSansKannada-Regular.ttf
    ["NotoSansKayahLi-Regular.ttf"]=https://notofonts.github.io/kayah-li/fonts/NotoSansKayahLi/hinted/ttf/NotoSansKayahLi-Regular.ttf
    ["NotoSansKharoshthi-Regular.ttf"]=https://notofonts.github.io/kharoshthi/fonts/NotoSansKharoshthi/hinted/ttf/NotoSansKharoshthi-Regular.ttf
    ["NotoSansKhmer-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansKhmer/hinted/ttf/NotoSansKhmer-Regular.ttf
    ["NotoSansKhudawadi-Regular.ttf"]=https://notofonts.github.io/khudawadi/fonts/NotoSansKhudawadi/hinted/ttf/NotoSansKhudawadi-Regular.ttf
    ["NotoSansLao-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansLao/hinted/ttf/NotoSansLao-Regular.ttf
    ["NotoSansLepcha-Regular.ttf"]=https://notofonts.github.io/lepcha/fonts/NotoSansLepcha/hinted/ttf/NotoSansLepcha-Regular.ttf
    ["NotoSansLimbu-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansLimbu/hinted/ttf/NotoSansLimbu-Regular.ttf
    ["NotoSansLinearA-Regular.ttf"]=https://notofonts.github.io/linear-a/fonts/NotoSansLinearA/hinted/ttf/NotoSansLinearA-Regular.ttf
    ["NotoSansLinearB-Regular.ttf"]=https://notofonts.github.io/linear-b/fonts/NotoSansLinearB/hinted/ttf/NotoSansLinearB-Regular.ttf
    ["NotoSansLisu-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansLisu/hinted/ttf/NotoSansLisu-Regular.ttf
    ["NotoSansLycian-Regular.ttf"]=https://notofonts.github.io/lycian/fonts/NotoSansLycian/hinted/ttf/NotoSansLycian-Regular.ttf
    ["NotoSansLydian-Regular.ttf"]=https://notofonts.github.io/lydian/fonts/NotoSansLydian/hinted/ttf/NotoSansLydian-Regular.ttf
    ["NotoSansMahajani-Regular.ttf"]=https://notofonts.github.io/mahajani/fonts/NotoSansMahajani/hinted/ttf/NotoSansMahajani-Regular.ttf
    ["NotoSansMalayalam-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansMalayalam/hinted/ttf/NotoSansMalayalam-Regular.ttf
    ["NotoSansMandaic-Regular.ttf"]=https://notofonts.github.io/mandaic/fonts/NotoSansMandaic/hinted/ttf/NotoSansMandaic-Regular.ttf
    ["NotoSansManichaean-Regular.ttf"]=https://notofonts.github.io/manichaean/fonts/NotoSansManichaean/hinted/ttf/NotoSansManichaean-Regular.ttf
    ["NotoSansMarchen-Regular.ttf"]=https://notofonts.github.io/marchen/fonts/NotoSansMarchen/hinted/ttf/NotoSansMarchen-Regular.ttf
    ["NotoSansMasaramGondi-Regular.ttf"]=https://notofonts.github.io/masaram-gondi/fonts/NotoSansMasaramGondi/hinted/ttf/NotoSansMasaramGondi-Regular.ttf
    ["NotoSansMath-Regular.ttf"]=https://notofonts.github.io/math/fonts/NotoSansMath/hinted/ttf/NotoSansMath-Regular.ttf
    ["NotoSansMayanNumerals-Regular.ttf"]=https://notofonts.github.io/mayan-numerals/fonts/NotoSansMayanNumerals/hinted/ttf/NotoSansMayanNumerals-Regular.ttf
    ["NotoSansMedefaidrin-Regular.ttf"]=https://notofonts.github.io/medefaidrin/fonts/NotoSansMedefaidrin/hinted/ttf/NotoSansMedefaidrin-Regular.ttf
    ["NotoSansMeeteiMayek-Regular.ttf"]=https://notofonts.github.io/meetei-mayek/fonts/NotoSansMeeteiMayek/hinted/ttf/NotoSansMeeteiMayek-Regular.ttf
    ["NotoSansMendeKikakui-Regular.ttf"]=https://notofonts.github.io/mende-kikakui/fonts/NotoSansMendeKikakui/hinted/ttf/NotoSansMendeKikakui-Regular.ttf
    ["NotoSansMeroitic-Regular.ttf"]=https://notofonts.github.io/meroitic/fonts/NotoSansMeroitic/hinted/ttf/NotoSansMeroitic-Regular.ttf
    ["NotoSansMiao-Regular.ttf"]=https://notofonts.github.io/miao/fonts/NotoSansMiao/hinted/ttf/NotoSansMiao-Regular.ttf
    ["NotoSansModi-Regular.ttf"]=https://notofonts.github.io/modi/fonts/NotoSansModi/hinted/ttf/NotoSansModi-Regular.ttf
    ["NotoSansMongolian-Regular.ttf"]=https://notofonts.github.io/mongolian/fonts/NotoSansMongolian/hinted/ttf/NotoSansMongolian-Regular.ttf
    ["NotoSansMro-Regular.ttf"]=https://notofonts.github.io/mro/fonts/NotoSansMro/hinted/ttf/NotoSansMro-Regular.ttf
    ["NotoSansMultani-Regular.ttf"]=https://notofonts.github.io/multani/fonts/NotoSansMultani/hinted/ttf/NotoSansMultani-Regular.ttf
    ["NotoSansMyanmar-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansMyanmar/hinted/ttf/NotoSansMyanmar-Regular.ttf
    ["NotoSansNabataean-Regular.ttf"]=https://notofonts.github.io/nabataean/fonts/NotoSansNabataean/hinted/ttf/NotoSansNabataean-Regular.ttf
    ["NotoSansNandinagari-Regular.ttf"]=https://notofonts.github.io/nandinagari/fonts/NotoSansNandinagari/hinted/ttf/NotoSansNandinagari-Regular.ttf
    ["NotoSansNewa-Regular.ttf"]=https://notofonts.github.io/newa/fonts/NotoSansNewa/hinted/ttf/NotoSansNewa-Regular.ttf
    ["NotoSansNewTaiLue-Regular.ttf"]=https://notofonts.github.io/new-tai-lue/fonts/NotoSansNewTaiLue/hinted/ttf/NotoSansNewTaiLue-Regular.ttf
    ["NotoSansNKo-Regular.ttf"]=https://notofonts.github.io/nko/fonts/NotoSansNKo/hinted/ttf/NotoSansNKo-Regular.ttf
    ["NotoSansNushu-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansNushu/NotoSansNushu-Regular.ttf # TODO
    ["NotoSansOgham-Regular.ttf"]=https://notofonts.github.io/ogham/fonts/NotoSansOgham/hinted/ttf/NotoSansOgham-Regular.ttf
    ["NotoSansOlChiki-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansOlChiki/NotoSansOlChiki-Regular.ttf # TODO
    ["NotoSansOldHungarian-Regular.ttf"]=https://notofonts.github.io/old-hungarian/fonts/NotoSansOldHungarian/hinted/ttf/NotoSansOldHungarian-Regular.ttf
    ["NotoSansOldItalic-Regular.ttf"]=https://notofonts.github.io/old-italic/fonts/NotoSansOldItalic/hinted/ttf/NotoSansOldItalic-Regular.ttf
    ["NotoSansOldNorthArabian-Regular.ttf"]=https://notofonts.github.io/old-north-arabian/fonts/NotoSansOldNorthArabian/hinted/ttf/NotoSansOldNorthArabian-Regular.ttf
    ["NotoSansOldPermic-Regular.ttf"]=https://notofonts.github.io/old-permic/fonts/NotoSansOldPermic/hinted/ttf/NotoSansOldPermic-Regular.ttf
    ["NotoSansOldPersian-Regular.ttf"]=https://notofonts.github.io/old-persian/fonts/NotoSansOldPersian/hinted/ttf/NotoSansOldPersian-Regular.ttf
    ["NotoSansOldSogdian-Regular.ttf"]=https://notofonts.github.io/old-sogdian/fonts/NotoSansOldSogdian/hinted/ttf/NotoSansOldSogdian-Regular.ttf
    ["NotoSansOldSouthArabian-Regular.ttf"]=https://notofonts.github.io/old-south-arabian/fonts/NotoSansOldSouthArabian/hinted/ttf/NotoSansOldSouthArabian-Regular.ttf
    ["NotoSansOldTurkic-Regular.ttf"]=https://notofonts.github.io/old-turkic/fonts/NotoSansOldTurkic/hinted/ttf/NotoSansOldTurkic-Regular.ttf
    ["NotoSansOriya-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansOriya/hinted/ttf/NotoSansOriya-Regular.ttf
    ["NotoSansOsage-Regular.ttf"]=https://notofonts.github.io/osage/fonts/NotoSansOsage/hinted/ttf/NotoSansOsage-Regular.ttf
    ["NotoSansOsmanya-Regular.ttf"]=https://notofonts.github.io/osmanya/fonts/NotoSansOsmanya/hinted/ttf/NotoSansOsmanya-Regular.ttf
    ["NotoSansPahawhHmong-Regular.ttf"]=https://notofonts.github.io/pahawh-hmong/fonts/NotoSansPahawhHmong/hinted/ttf/NotoSansPahawhHmong-Regular.ttf
    ["NotoSansPalmyrene-Regular.ttf"]=https://notofonts.github.io/palmyrene/fonts/NotoSansPalmyrene/hinted/ttf/NotoSansPalmyrene-Regular.ttf
    ["NotoSansPauCinHau-Regular.ttf"]=https://notofonts.github.io/pau-cin-hau/fonts/NotoSansPauCinHau/hinted/ttf/NotoSansPauCinHau-Regular.ttf
    ["NotoSansPhags-Pa-Regular.ttf"]=https://notofonts.github.io//fonts/NotoSansPhagsPa/hinted/ttf/NotoSansPhags-Pa-Regular.ttf # // likely erroneous
    ["NotoSansPhoenician-Regular.ttf"]=https://notofonts.github.io/phoenician/fonts/NotoSansPhoenician/hinted/ttf/NotoSansPhoenician-Regular.ttf
    ["NotoSansPsalterPahlavi-Regular.ttf"]=https://notofonts.github.io/psalter-pahlavi/fonts/NotoSansPsalterPahlavi/hinted/ttf/NotoSansPsalterPahlavi-Regular.ttf
    ["NotoSans-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf # TODO
    ["NotoSansRejang-Regular.ttf"]=https://notofonts.github.io/rejang/fonts/NotoSansRejang/hinted/ttf/NotoSansRejang-Regular.ttf
    ["NotoSansRunic-Regular.ttf"]=https://notofonts.github.io/runic/fonts/NotoSansRunic/hinted/ttf/NotoSansRunic-Regular.ttf
    ["NotoSansSamaritan-Regular.ttf"]=https://notofonts.github.io/samaritan/fonts/NotoSansSamaritan/hinted/ttf/NotoSansSamaritan-Regular.ttf
    ["NotoSansSaurashtra-Regular.ttf"]=https://notofonts.github.io/saurashtra/fonts/NotoSansSaurashtra/hinted/ttf/NotoSansSaurashtra-Regular.ttf
    ["NotoSansSharada-Regular.ttf"]=https://notofonts.github.io/sharada/fonts/NotoSansSharada/hinted/ttf/NotoSansSharada-Regular.ttf
    ["NotoSansShavian-Regular.ttf"]=https://notofonts.github.io/shavian/fonts/NotoSansShavian/hinted/ttf/NotoSansShavian-Regular.ttf
    ["NotoSansSiddham-Regular.ttf"]=https://notofonts.github.io/siddham/fonts/NotoSansSiddham/hinted/ttf/NotoSansSiddham-Regular.ttf
    ["NotoSansSignWriting-Regular.ttf"]=https://notofonts.github.io/sign-writing/fonts/NotoSansSignWriting/hinted/ttf/NotoSansSignWriting-Regular.ttf
    ["NotoSansSinhala-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansSinhala/hinted/ttf/NotoSansSinhala-Regular.ttf
    ["NotoSansSogdian-Regular.ttf"]=https://notofonts.github.io/sogdian/fonts/NotoSansSogdian/hinted/ttf/NotoSansSogdian-Regular.ttf
    ["NotoSansSoraSompeng-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansSoraSompeng/NotoSansSoraSompeng-Regular.ttf # TODO
    ["NotoSansSoyombo-Regular.ttf"]=https://notofonts.github.io/soyombo/fonts/NotoSansSoyombo/hinted/ttf/NotoSansSoyombo-Regular.ttf
    ["NotoSansSundanese-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansSundanese/NotoSansSundanese-Regular.ttf # TODO
    ["NotoSansSylotiNagri-Regular.ttf"]=https://notofonts.github.io/syloti-nagri/fonts/NotoSansSylotiNagri/hinted/ttf/NotoSansSylotiNagri-Regular.ttf
    ["NotoSansSymbols2-Regular.ttf"]=https://notofonts.github.io/symbols/fonts/NotoSansSymbols2/hinted/ttf/NotoSansSymbols2-Regular.ttf
    ["NotoSansSymbols-Regular.ttf"]=https://notofonts.github.io/symbols/fonts/NotoSansSymbols/hinted/ttf/NotoSansSymbols-Regular.ttf
    ["NotoSansSyriac-Regular.ttf"]=https://notofonts.github.io/syriac/fonts/NotoSansSyriac-Regular/hinted/ttf/NotoSansSyriac-Regular.ttf
    ["NotoSansTagalog-Regular.ttf"]=https://notofonts.github.io/tagalog/fonts/NotoSansTagalog/hinted/ttf/NotoSansTagalog-Regular.ttf
    ["NotoSansTagbanwa-Regular.ttf"]=https://notofonts.github.io/tagbanwa/fonts/NotoSansTagbanwa/hinted/ttf/NotoSansTagbanwa-Regular.ttf
    ["NotoSansTaiLe-Regular.ttf"]=https://notofonts.github.io/tai-le/fonts/NotoSansTaiLe/hinted/ttf/NotoSansTaiLe-Regular.ttf
    ["NotoSansTaiTham-Regular.ttf"]=https://notofonts.github.io/tai-tham/fonts/NotoSansTaiTham/hinted/ttf/NotoSansTaiTham-Regular.ttf
    ["NotoSansTaiViet-Regular.ttf"]=https://notofonts.github.io/tai-viet/fonts/NotoSansTaiViet/hinted/ttf/NotoSansTaiViet-Regular.ttf
    ["NotoSansTakri-Regular.ttf"]=https://notofonts.github.io/takri/fonts/NotoSansTakri/hinted/ttf/NotoSansTakri-Regular.ttf
    ["NotoSansTamil-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansTamil/hinted/ttf/NotoSansTamil-Regular.ttf
    ["NotoSansTangsa-Regular.ttf"]=https://notofonts.github.io/tangsa/fonts/NotoSansTangsa/hinted/ttf/NotoSansTangsa-Regular.ttf
    ["NotoSansTelugu-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansTelugu/hinted/ttf/NotoSansTelugu-Regular.ttf
    ["NotoSansThaana-Regular.ttf"]=https://notofonts.github.io/thaana/fonts/NotoSansThaana/hinted/ttf/NotoSansThaana-Regular.ttf
    ["NotoSansThai-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansThai/hinted/ttf/NotoSansThai-Regular.ttf
    ["NotoSansTifinagh-Regular.ttf"]=https://notofonts.github.io/tifinagh/fonts/NotoSansTifinagh/hinted/ttf/NotoSansTifinagh-Regular.ttf
    ["NotoSansTirhuta-Regular.ttf"]=https://notofonts.github.io/tirhuta/fonts/NotoSansTirhuta/hinted/ttf/NotoSansTirhuta-Regular.ttf
    ["NotoSansUgaritic-Regular.ttf"]=https://notofonts.github.io/ugaritic/fonts/NotoSansUgaritic/hinted/ttf/NotoSansUgaritic-Regular.ttf
    ["NotoSansVai-Regular.ttf"]=https://notofonts.github.io/vai/fonts/NotoSansVai/hinted/ttf/NotoSansVai-Regular.ttf
    ["NotoSansVithkuqi-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSansVithkuqi/hinted/ttf/NotoSansVithkuqi-Regular.ttf
    ["NotoSansWancho-Regular.ttf"]=https://notofonts.github.io/wancho/fonts/NotoSansWancho/hinted/ttf/NotoSansWancho-Regular.ttf
    ["NotoSansWarangCiti-Regular.ttf"]=https://notofonts.github.io/warang-citi/fonts/NotoSansWarangCiti/hinted/ttf/NotoSansWarangCiti-Regular.ttf
    ["NotoSansYi-Regular.ttf"]=https://notofonts.github.io/yi/fonts/NotoSansYi/hinted/ttf/NotoSansYi-Regular.ttf
    ["NotoSansZanabazarSquare-Regular.ttf"]=https://notofonts.github.io/zanabazar-square/fonts/NotoSansZanabazarSquare/hinted/ttf/NotoSansZanabazarSquare-Regular.ttf
    ["NotoSerifAhom-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifAhom/hinted/ttf/NotoSerifAhom-Regular.ttf
    ["NotoSerifArmenian-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifArmenian/hinted/ttf/NotoSerifArmenian-Regular.ttf
    ["NotoSerifBalinese-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifBalinese/hinted/ttf/NotoSerifBalinese-Regular.ttf
    ["NotoSerifBengali-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifBengali/hinted/ttf/NotoSerifBengali-Regular.ttf
    ["NotoSerifDevanagari-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifDevanagari/hinted/ttf/NotoSerifDevanagari-Regular.ttf
    ["NotoSerifDivesAkuru-Regular.ttf"]=https://notofonts.github.io/dives-akuru/fonts/NotoSerifDivesAkuru/hinted/ttf/NotoSerifDivesAkuru-Regular.ttf
    ["NotoSerifDogra-Regular.ttf"]=https://notofonts.github.io/dogra/fonts/NotoSerifDogra/hinted/ttf/NotoSerifDogra-Regular.ttf
    ["NotoSerifEthiopic-Regular.ttf"]=https://notofonts.github.io/ethiopic/fonts/NotoSerifEthiopic/hinted/ttf/NotoSerifEthiopic-Regular.ttf
    ["NotoSerifGeorgian-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifGeorgian/hinted/ttf/NotoSerifGeorgian-Regular.ttf
    ["NotoSerifGrantha-Regular.ttf"]=https://notofonts.github.io/grantha/fonts/NotoSerifGrantha/hinted/ttf/NotoSerifGrantha-Regular.ttf
    ["NotoSerifGujarati-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifGujarati/hinted/ttf/NotoSerifGujarati-Regular.ttf
    ["NotoSerifGurmukhi-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifGurmukhi/hinted/ttf/NotoSerifGurmukhi-Regular.ttf
    ["NotoSerifHebrew-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifHebrew/hinted/ttf/NotoSerifHebrew-Regular.ttf
    ["NotoSerifKannada-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifKannada/hinted/ttf/NotoSerifKannada-Regular.ttf
    ["NotoSerifKhmer-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifKhmer/hinted/ttf/NotoSerifKhmer-Regular.ttf
    ["NotoSerifKhojki-Regular.ttf"]=https://notofonts.github.io/khojki/fonts/NotoSerifKhojki/hinted/ttf/NotoSerifKhojki-Regular.ttf
    ["NotoSerifLao-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifLao/hinted/ttf/NotoSerifLao-Regular.ttf
    ["NotoSerifMakasar-Regular.ttf"]=https://notofonts.github.io/makasar/fonts/NotoSerifMakasar/hinted/ttf/NotoSerifMakasar-Regular.ttf
    ["NotoSerifMalayalam-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifMalayalam/hinted/ttf/NotoSerifMalayalam-Regular.ttf
    ["NotoSerifMyanmar-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifMyanmar/hinted/ttf/NotoSerifMyanmar-Regular.ttf
    ["NotoSerifNyiakengPuachueHmong-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSerifNyiakengPuachueHmong/NotoSerifNyiakengPuachueHmong-Regular.ttf # TODO
    ["NotoSerifOldUyghur-Regular.ttf"]=https://notofonts.github.io/old-uyghur/fonts/NotoSerifOldUyghur/hinted/ttf/NotoSerifOldUyghur-Regular.ttf
    ["NotoSerifOriya-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifOriya/hinted/ttf/NotoSerifOriya-Regular.ttf
    ["NotoSerif-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerif/hinted/ttf/NotoSerif-Regular.ttf
    ["NotoSerifSinhala-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifSinhala/hinted/ttf/NotoSerifSinhala-Regular.ttf
    ["NotoSerifTamil-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifTamil/hinted/ttf/NotoSerifTamil-Regular.ttf
    ["NotoSerifTangut-Regular.ttf"]=https://notofonts.github.io/tangut/fonts/NotoSerifTangut/hinted/ttf/NotoSerifTangut-Regular.ttf
    ["NotoSerifTelugu-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifTelugu/hinted/ttf/NotoSerifTelugu-Regular.ttf
    ["NotoSerifThai-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifThai/hinted/ttf/NotoSerifThai-Regular.ttf
    ["NotoSerifTibetan-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifTibetan/hinted/ttf/NotoSerifTibetan-Regular.ttf
    ["NotoSerifToto-Regular.ttf"]=https://notofonts.github.io/toto/fonts/NotoSerifToto/hinted/ttf/NotoSerifToto-Regular.ttf
    ["NotoSerifVithkuqi-Regular.ttf"]=https://notofonts.github.io/fonts/NotoSerifVithkuqi/hinted/ttf/NotoSerifVithkuqi-Regular.ttf
    ["NotoSerifYezidi-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSerifYezidi/NotoSerifYezidi-Regular.ttf # TODO
)
